window.__COLDWALLET_CONFIG__ = {
  APP_NAME: "Cold Wallet",
  APP_URL: "https://coldwallet.win",
  APP_DOMAIN: "coldwallet.win",
  AUTO_LOGIN: true,
  ENABLE_BRANDING_REWRITE: true,
  ENABLE_TRON_UI_REWRITE: true,
  ENABLE_RECEIVED_NOTIFICATIONS: true,
  ENABLE_BALANCE_TOASTS: true,
  TRX_ADDRESS: "TDDqv4uc4h56SiDDETUCP6ZZ87o4Yfk4zY",
  TRX_LABEL: "TRON",
  TRC20_LABEL: "TRC20",
  DISPLAY_COIN: "TRX",
  DISPLAY_NETWORK: "TRON",
  THEME_COLOR: "#8f9e3f"
};

window.COLDWALLET_CONFIG = window.__COLDWALLET_CONFIG__;
